services:
  gkg-deployed:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gkg-server-deployed
    # Running as root, data dir can be anywhere.
    command: ["http-server-deployed", "-m", "webserver", "--bind", "0.0.0.0:3334", "--secret-path", "/secrets/jwt.secret", "--data-dir", "/data/gkg-deployed"]
    ports:
      - "3334:3334"
    volumes:
      - gkg-data-deployed:/data/gkg-deployed
      - ./jwt.secret:/secrets/jwt.secret:ro
      - ./:/workspace:ro
    environment:
      - RUST_LOG=info
    restart: unless-stopped

  gkg-desktop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gkg-server-desktop
    command: ["dev-server", "--enable-reindexing"]
    ports:
      - "27495:27495"
    volumes:
      # The dev-server will use /root/.gkg as its data path when run as root
      - gkg-data-desktop:/root/.gkg
      - ./:/workspace:ro
    environment:
      - RUST_LOG=info
      - DEV_PORT=27495
volumes:
  gkg-data-deployed:
    driver: local
  gkg-data-desktop:
    driver: local