stages:
  - lint
  - build
  - test
  - benchmark
  - deploy
  
variables:
  KUZU_VERSION: "0.11.0"

.rust-job-template:
  tags:
    - saas-linux-large-amd64
  image: registry.gitlab.com/gitlab-org/rust/build-images/rust-kuzu:1.88.0-${KUZU_VERSION}-linux-x86_64
  before_script:
    - rustup set auto-self-update disable

mr-title-check:
  image: ${GITLAB_DEPENDENCY_PROXY}node:lts-alpine
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - npm install -g @commitlint/cli @commitlint/config-conventional
  script:
    - ./scripts/check-mr-title.sh

rust-fmt-check:
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - cargo fmt --check
  extends: .rust-job-template

rust-lint-check:
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - cargo clippy --all-targets --all-features -- -D warnings  
  extends: .rust-job-template

xtask-version-check:
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - cargo run --package xtask --manifest-path crates/xtask/Cargo.toml -- check-versions
  extends: .rust-job-template

frontend-build:
  stage: build
  image: node:22.17.0
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - npm ci
  script:
    - npm run build --workspace=@gitlab-org/gkg-frontend
    - npm run build --workspace=@gitlab-org/gkg
  artifacts:
    paths:
      - packages/frontend/dist/
    expire_in: 24 hours


rust-unit-test-report:
  stage: test
  needs:
    - frontend-build
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    RUST_BACKTRACE: 1
  script:
    - cargo test export_bindings_ && cargo nextest run --profile ci
  extends: .rust-job-template
  artifacts:
    when: always
    reports:
      junit:
        - target/nextest/ci/junit.xml

# Reusable script for installing gitlab-xtasks conditionally
.install-gitlab-xtasks: &install-gitlab-xtasks |
    cargo install --git https://gitlab.com/gitlab-org/rust/gitlab-xtasks --tag v1.1.0 --force


# Shared benchmark template for GKG indexing performance tests
.gkg-benchmark-template:
  stage: benchmark
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  interruptible: true
  script:
    - export CARGO_INSTALL_ROOT="${CARGO_HOME:-$HOME/.cargo}"
    - export PATH="${CARGO_INSTALL_ROOT}/bin:$HOME/.cargo/bin:$PATH"
    - *install-gitlab-xtasks
    - |
      # Debug: Show where gitlab-xtasks was installed
      which gitlab-xtasks || echo "gitlab-xtasks not found in PATH"
      echo "Current PATH: $PATH"
      
      # Platform-specific setup
      if [[ "$RUNNER_OS" == "macOS" ]]; then
        # rustup will automatically use the version from rust-toolchain.toml
        # Install hyperfine via Homebrew (recommended method)
        brew install hyperfine 2>/dev/null || echo "hyperfine may already be installed"
      else
        cargo install --locked hyperfine
      fi
      
      # Run benchmark with unique filename
      OUTPUT_FILE="gkg-benchmark-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-${ARCH}-${SCENARIO}.json"
      gitlab-xtasks benchmark hyperfine \
        --config gkg-benchmark-config.toml \
        --architecture "$ARCH" \
        --scenario "$SCENARIO" \
        --output-file "$OUTPUT_FILE"
      echo "GKG benchmark completed for scenario: $SCENARIO on architecture: $ARCH"
  artifacts:
    paths:
      - gkg-benchmark-*.json
    expire_in: 3 weeks

# Linux GKG benchmark execution
gkg-benchmark-linux:
  extends: 
    - .rust-job-template
    - .gkg-benchmark-template
  variables:
    ARCH: "linux-x86_64"
    CARGO_HOME: ${CI_PROJECT_DIR}/.cargo
  parallel:
    matrix:
      - SCENARIO: [gkg_index_gdk_release_4_threads]

gkg-benchmark-macos:
  extends: .gkg-benchmark-template
  tags:
    - saas-macos-medium-m1
  image: macos-15-xcode-16
  variables:
    ARCH: "macos-arm64"
    RUNNER_OS: "macOS"
  before_script:
    - source ./scripts/macos-kuzu-install.sh
    - rustc --version && cargo --version
    - rustup set auto-self-update disable
  parallel:
    matrix:
      - SCENARIO: [gkg_index_gdk_release_4_threads]

# Collect and analyze all GKG benchmark results
gkg-benchmark-analyze:
  stage: benchmark
  needs: 
    - gkg-benchmark-linux
    - gkg-benchmark-macos
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  interruptible: true
  script:
    - *install-gitlab-xtasks
    - |
      # Generate markdown report with metadata
      gitlab-xtasks benchmark analyze \
        --pattern "gkg-benchmark-*.json" \
        --output-format markdown \
        --pipeline-url "$CI_PIPELINE_URL" \
        --job-url "$CI_JOB_URL" \
        --branch "$CI_COMMIT_REF_NAME" \
        --output-file gkg-benchmark-results.md
      
      # Generate JSON report with metadata  
      gitlab-xtasks benchmark analyze \
        --pattern "gkg-benchmark-*.json" \
        --output-format json \
        --pipeline-url "$CI_PIPELINE_URL" \
        --job-url "$CI_JOB_URL" \
        --branch "$CI_COMMIT_REF_NAME" \
        --output-file gkg-benchmark-results.json
      
      echo "Generated GKG benchmark reports:"
      echo "- Markdown: gkg-benchmark-results.md"
      echo "- JSON: gkg-benchmark-results.json"
      
      # Post benchmark results as MR comment using delete-and-add strategy
      if [[ -n "$CI_MERGE_REQUEST_IID" ]]; then
        echo "Posting GKG benchmark results to MR !$CI_MERGE_REQUEST_IID..."
        gitlab-xtasks comment post \
          --type delete-and-add \
          --unique-id "gkg-benchmarking-comment" \
          --file-path gkg-benchmark-results.md
        echo "GKG benchmark comment posted successfully"
      else
        echo "Not a merge request pipeline, skipping comment posting"
      fi
  artifacts:
    paths:
      - gkg-benchmark-results.md
      - gkg-benchmark-results.json
      - gkg-benchmark-*.json
    expire_in: 1 week
  extends: .rust-job-template

cargo-update:
  stage: deploy
  extends: .rust-job-template
  script:
    - cargo update --workspace
    - cp Cargo.lock Cargo.lock.new
  artifacts:
    paths:
      - Cargo.lock.new
    expire_in: 7 days
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

.linux-build-template:
  image: rust:1.88.0-bookworm
  stage: deploy
  needs:
    - frontend-build
    - cargo-update
  before_script:
    - rm -f Cargo.lock
    - mv Cargo.lock.new Cargo.lock
  script:
    - apt-get update && apt-get install -y build-essential cmake gcc g++ python3
    - rustup target add ${ARCH}-unknown-linux-gnu
    - ./scripts/build.sh
  variables:
    PLATFORM: Linux
  artifacts:
    paths:
      - ./gkg-linux-${ARCH}.tar.gz
      - ./lib
    expire_in: 7 days
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

.darwin-build-template:
  image: macos-15-xcode-16
  tags:
    - saas-macos-medium-m1
  stage: deploy
  needs:
    - frontend-build
    - cargo-update
  before_script:
    - rm -f Cargo.lock
    - mv Cargo.lock.new Cargo.lock
  script:
    - brew install cmake python jq
    - rustup target add ${ARCH}-apple-darwin
    - ./scripts/build.sh
  variables:
    PLATFORM: Darwin
  artifacts:
    paths:
      - ./gkg-darwin-${ARCH}.tar.gz
      - ./lib
    expire_in: 7 days
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build:linux-aarch64-gnu:
  extends: .linux-build-template
  tags:
    - saas-linux-large-arm64
  variables:
    ARCH: aarch64

build:linux-x86_64-gnu:
  extends: .linux-build-template
  tags:
    - saas-linux-large-amd64
  variables:
    ARCH: x86_64

build:darwin-aarch64:
  extends: .darwin-build-template
  variables:
    ARCH: aarch64

build:darwin-x86_64:
  extends: .darwin-build-template
  variables:
    ARCH: x86_64

build:windows-x86_64:
  tags:
    - saas-windows-medium-amd64
  stage: deploy
  needs:
    - frontend-build
    - cargo-update
  before_script:
    - '.\scripts\windows-prepare.ps1 ${KUZU_VERSION}'
    - Remove-Item -Path Cargo.lock -ErrorAction SilentlyContinue
    - Move-Item -Path Cargo.lock.new -Destination Cargo.lock
  script:
    - cargo build --release --bin gkg --locked
    - Copy-Item -Path C:\install\libkuzu\*.dll -Destination target\release\
    - tar -czvf gkg-windows-x86_64.tar.gz -C target/release gkg.exe *.dll
  artifacts:
    paths:
      - ./gkg-windows-x86_64.tar.gz
    expire_in: 7 days
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  timeout: 2h

.go-job-template:
  image: ${GITLAB_DEPENDENCY_PROXY}golang:1.24.5
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    key:
      files:
        - .gitlab-ci.yml
    paths:
      - .go/pkg/mod/

build-bindings:
  image: rust:1.88.0-bookworm
  stage: build
  allow_failure: true
  when: manual
  tags:
    - saas-linux-large-amd64
  script:
    - apt-get update && apt-get install -y build-essential cmake gcc g++ python3
    - rustup target add ${ARCH}-unknown-linux-gnu
    - ./scripts/build.sh lib
  variables:
    PLATFORM: Linux
    ARCH: x86_64
    CARGO_PARAMS: '--release'
  artifacts:
    paths:
      - ./gkg-linux-${ARCH}.tar.gz
      - ./lib
    expire_in: 7 days
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

go-tests:
  stage: test
  allow_failure: true
  needs:
    - build-bindings
  script:
    - cd bindings/go/
    - go test ./...
  extends: .go-job-template
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

publish-release::manual:
  image: registry.gitlab.com/gitlab-org/editor-extensions/build-images/node-codesign:22.14.0
  stage: deploy
  needs:
    - build:linux-aarch64-gnu
    - build:linux-x86_64-gnu
    - build:darwin-aarch64
    - build:darwin-x86_64
    - build:windows-x86_64
    - cargo-update
  before_script:
    # Install git-lfs to handle large library files
    - apt update && apt install -y git-lfs
    # Use the new Cargo.lock from cargo-update step
    - rm -f Cargo.lock
    - mv Cargo.lock.new Cargo.lock
    # Validate that the repository contains a package.json and extract a few values from it.
    - |
      if [[ ! -f package.json ]]; then
        echo "No package.json found! A package.json file is required to publish a package to GitLab's NPM registry."
        echo 'For more information, see https://docs.gitlab.com/ee/user/packages/npm_registry/#creating-a-project'
        exit 1
      fi
    - NPM_PACKAGE_NAME=$(node -p "require('./package.json').name")
    - NPM_PACKAGE_VERSION=$(node -p "require('./package.json').version")
    # Validate that the package name is properly scoped to the project's root namespace.
    # For more information, see https://docs.gitlab.com/user/packages/npm_registry/#naming-convention
    - |
      if [[ ! $NPM_PACKAGE_NAME =~ ^@$CI_PROJECT_ROOT_NAMESPACE/ ]]; then
        echo "Invalid package scope! Packages must be scoped in the root namespace of the project, e.g. \"@${CI_PROJECT_ROOT_NAMESPACE}/${CI_PROJECT_NAME}\""
        echo 'For more information, see https://docs.gitlab.com/user/packages/npm_registry/#naming-convention'
        exit 1
      fi
  script:
    - npm ci
    - PREVIOUS_VERSION=$(node -p "require('./package.json').version")
    # Generate SHA256 checksums for all binaries
    - for file in *.tar.gz; do if [ -f "$file" ]; then sha256sum "$file" > "${file}.sha256"; fi; done
    - npm run semantic-release
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  allow_failure: false
