// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmptyRequest, HttpMethod } from "../../../packages/gkg/src/api";

export type EventsEndpointDef = { method: HttpMethod, path: "/api/events", path_request: EmptyRequest, body_request: EmptyRequest, query_request: EmptyRequest, responses: EventsResponses, };

export type EventsResponses = Record<string, never>;
