// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiContract = { root: RootEndpointDef, workspace_index: WorkspaceIndexEndpointDef, };

export type EmptyRequest = null;

export type HttpMethod = "GET" | "POST";

export type IndexingProgressResponse = { message: string, };

export type RootEndpointDef = { method: HttpMethod, path: "/", path_request: EmptyRequest, body_request: EmptyRequest, query_request: EmptyRequest, responses: RootResponses, };

export type RootResponses = { "200": ServerInfoResponse, };

export type ServerInfoResponse = { port: number, };

export type StatusResponse = { status: string, };

export type WorkspaceIndexBodyRequest = { workspace: string, };

export type WorkspaceIndexEndpointDef = { method: HttpMethod, path: "/workspace/index", path_request: EmptyRequest, body_request: WorkspaceIndexBodyRequest, query_request: EmptyRequest, responses: WorkspaceIndexResponses, };

export type WorkspaceIndexResponses = { "200": IndexingProgressResponse | null, "400": StatusResponse | null, "409": StatusResponse | null, };
