# Docker Compose file for building and running the knowledge-graph services with nginx-proxy and acme-companion
services:
  gkg-cli:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
      target: cli
    container_name: gkg-cli
    volumes:
      - ${WORKSPACE_PATH}:/workspace:ro
      - gkg-data:/root/.gkg
    restart: unless-stopped

  gkg-webserver:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
      target: webserver
    container_name: gkg-webserver
    ports:
      - "3334:3334"
    volumes:
      - gkg-data:/root/.gkg
      - ${JWT_SECRET}:/secrets/jwt.secret:ro
    env_file: ../../.env
    restart: unless-stopped

  gkg-indexer:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
      target: indexer
    container_name: gkg-indexer
    ports:
      - "3333:3333"
    volumes:
      - gkg-data:/root/.gkg
      - ${JWT_SECRET}:/secrets/jwt.secret:ro
    env_file: ../../.env
    restart: unless-stopped

  gkg-desktop:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
      target: desktop
    container_name: gkg-desktop
    ports:
      - "27495:27495"
    volumes:
      - ${WORKSPACE_PATH}:/workspace:ro
      - gkg-data:/root/.gkg
    env_file: ../../.env
    environment:
      DEV_PORT: 27495
    restart: unless-stopped

volumes:
  gkg-data: