// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSWorkspaceFolderInfo } from "./workspace_folder";

export type ApiContract = { info: InfoEndpointDef, workspace_index: WorkspaceIndexEndpointDef, };

export type EmptyRequest = null;

export type HttpMethod = "GET" | "POST";

export type InfoEndpointDef = { method: HttpMethod, path: "/api/info", path_request: EmptyRequest, body_request: EmptyRequest, query_request: EmptyRequest, responses: InfoResponses, };

export type InfoResponses = { "200": ServerInfoResponse, };

export type ServerInfoResponse = { port: number, };

export type StatusResponse = { status: string, };

export type WorkspaceIndexBodyRequest = { workspace: string, };

export type WorkspaceIndexEndpointDef = { method: HttpMethod, path: "/api/workspace/index", path_request: EmptyRequest, body_request: WorkspaceIndexBodyRequest, query_request: EmptyRequest, responses: WorkspaceIndexResponses, };

export type WorkspaceIndexResponses = { ok: TSWorkspaceFolderInfo | null, bad_request: StatusResponse | null, internal_server_error: StatusResponse | null, };
