// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSProjectInfo } from "./project_info";
import type { TSWorkspaceFolderInfo } from "./workspace_folder";

export type ApiContract = { info: InfoEndpointDef, workspace_index: WorkspaceIndexEndpointDef, workspace_list: WorkspaceListEndpointDef, workspace_delete: WorkspaceDeleteEndpointDef, index: WorkspaceIndexEndpointDef, events: EventsEndpointDef, graph_initial: GraphInitialEndpointDef, };

export type DefinitionNodeProperties = { path: string, fqn: string, definition_type: string, primary_line_number: number, primary_start_byte: bigint, primary_end_byte: bigint, total_locations: number, };

export type DirectoryNodeProperties = { path: string, absolute_path: string, repository_name: string, };

export type EmptyRequest = null;

export type EventsEndpointDef = { method: HttpMethod, path: "/api/events", path_request: EmptyRequest, body_request: EmptyRequest, query_request: EmptyRequest, responses: EventsResponses, };

export type EventsResponses = Record<string, never>;

export type FileNodeProperties = { path: string, absolute_path: string, repository_name: string, language: string, extension: string, };

export type GraphInitialEndpointDef = { method: HttpMethod, path: "/api/graph/initial/{workspace_folder_path}/{project_path}", path_request: GraphInitialPathRequest, body_request: EmptyRequest, query_request: GraphInitialQueryRequest, responses: GraphInitialSuccessResponse, };

export type GraphInitialPathRequest = { workspace_folder_path: string, project_path: string, };

export type GraphInitialQueryRequest = { directory_limit: number | null, file_limit: number | null, definition_limit: number | null, };

export type GraphInitialResponses = { "200": GraphInitialSuccessResponse | null, "404": StatusResponse | null, "400": StatusResponse | null, "500": StatusResponse | null, };

export type GraphInitialSuccessResponse = { nodes: Array<TypedGraphNode>, relationships: Array<GraphRelationship>, project_info: TSProjectInfo, };

export type GraphRelationship = { id: string, source: string, target: string, relationship_type: string, properties: Record<string, any>, };

export type HttpMethod = "GET" | "POST" | "DELETE";

export type InfoEndpointDef = { method: HttpMethod, path: "/api/info", path_request: EmptyRequest, body_request: EmptyRequest, query_request: EmptyRequest, responses: InfoResponses, };

export type InfoResponses = { "200": ServerInfoResponse, };

/**
 * Job types that can be processed by the queue system.
 *
 * Each job variant represents a different type of work that can be performed.
 * Jobs are routed to workspace-specific queues for sequential processing.
 */
export type Job = { "type": "IndexWorkspaceFolder", "data": { workspace_folder_path: string, priority: JobPriority, } };

export type JobInfo = { id: string, job: Job, created_at: string, started_at: string | null, completed_at: string | null, status: JobStatus, error: string | null, };

/**
 * Priority levels for job processing.
 *
 * Higher priority jobs can cancel existing lower priority jobs for the same workspace.
 * This ensures user-triggered or high-priority operations take precedence over background tasks.
 */
export type JobPriority = "Low" | "Normal" | "High";

export type JobStatus = "Pending" | "Running" | "Completed" | "Failed" | "Cancelled";

export type ServerInfoResponse = { port: number, version: string, };

export type StatusResponse = { status: string, };

export type TypedGraphNode = { "node_type": "DirectoryNode", id: string, label: string, properties: DirectoryNodeProperties, } | { "node_type": "FileNode", id: string, label: string, properties: FileNodeProperties, } | { "node_type": "DefinitionNode", id: string, label: string, properties: DefinitionNodeProperties, };

export type WorkspaceDeleteBodyRequest = { workspace_folder_path: string, };

export type WorkspaceDeleteEndpointDef = { method: HttpMethod, path: "/api/workspace/delete", path_request: EmptyRequest, body_request: WorkspaceDeleteBodyRequest, query_request: EmptyRequest, responses: WorkspaceDeleteResponses, };

export type WorkspaceDeleteResponses = { "200": WorkspaceDeleteSuccessResponse, "400": StatusResponse, "404": StatusResponse, "500": StatusResponse, };

export type WorkspaceDeleteSuccessResponse = { workspace_folder_path: string, removed: boolean, };

export type WorkspaceIndexBodyRequest = { workspace_folder_path: string, };

export type WorkspaceIndexEndpointDef = { method: HttpMethod, path: "/api/workspace/index", path_request: EmptyRequest, body_request: WorkspaceIndexBodyRequest, query_request: EmptyRequest, responses: WorkspaceIndexResponses, };

export type WorkspaceIndexResponses = { "200": TSWorkspaceFolderInfo, "400": StatusResponse, "500": StatusResponse, };

export type WorkspaceListEndpointDef = { method: HttpMethod, path: "/api/workspace/list", path_request: EmptyRequest, body_request: EmptyRequest, query_request: EmptyRequest, responses: WorkspaceListResponses, };

export type WorkspaceListResponses = { "200": WorkspaceListSuccessResponse, "500": StatusResponse, };

export type WorkspaceListSuccessResponse = { workspaces: Array<WorkspaceWithProjects>, };

export type WorkspaceWithProjects = { workspace_info: TSWorkspaceFolderInfo, projects: Array<TSProjectInfo>, };
