// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSProjectInfo } from "./project_info";
import type { TSWorkspaceFolderInfo } from "./workspace_folder";

export type GkgEvent = { "type": "WorkspaceIndexing", "payload": WorkspaceIndexingEvent } | { "type": "ProjectIndexing", "payload": ProjectIndexingEvent };

export type ProjectIndexingCompleted = { project_info: TSProjectInfo, completed_at: string, };

export type ProjectIndexingEvent = { "status": "Started" } & ProjectIndexingStarted | { "status": "Completed" } & ProjectIndexingCompleted | { "status": "Failed" } & ProjectIndexingFailed;

export type ProjectIndexingFailed = { project_info: TSProjectInfo, error: string, failed_at: string, };

export type ProjectIndexingStarted = { project_info: TSProjectInfo, started_at: string, };

export type WorkspaceIndexingCompleted = { workspace_folder_info: TSWorkspaceFolderInfo, projects_indexed: Array<string>, completed_at: string, };

export type WorkspaceIndexingEvent = { "status": "Started" } & WorkspaceIndexingStarted | { "status": "Project" } & ProjectIndexingEvent | { "status": "Completed" } & WorkspaceIndexingCompleted | { "status": "Failed" } & WorkspaceIndexingFailed;

export type WorkspaceIndexingFailed = { workspace_folder_info: TSWorkspaceFolderInfo, projects_indexed: Array<string>, error: string, failed_at: string, };

export type WorkspaceIndexingStarted = { workspace_folder_info: TSWorkspaceFolderInfo, projects_to_process: Array<string>, started_at: string, };
