[package]
name = "indexer-c-bindings"
version = "0.10.0"
edition = "2024"
description = "GitLab Knowledge Graph C Bindings - Server side indexing"

[lib]
name = "indexer_c_bindings"
crate-type = ["staticlib"]

[dependencies]
indexer = { path = "../indexer" }
tokio = { workspace = true }
