# Configuration for cbindgen

language = "C"

# Don't include a header guard (Go's cgo doesn't handle them well)
no_includes = true

# Indicate we're using structs
[export]
include = ["CRelativeImport", "CImportArray", "CSymbolInfo", "CSymbolArray", "CSymbolKind"]

# We might need to specify custom types if there are any issues
[defines]
