[package]
name = "gkg"
version = "0.4.0"
edition = "2024"
description = "GitLab Knowledge Graph CLI"

[dependencies]
indexer = { path = "../indexer" }
workspace-manager = { path = "../workspace-manager" }
http-server = { path = "../http-server" }
mcp = { path = "../mcp" }
logging = { path = "../logging" }
event-bus = { path = "../event-bus" }
parser-core = { workspace = true }
gitalisk-core = { workspace = true }
clap = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
num_cpus = { workspace = true }
single-instance = { workspace = true }
home = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true }
ctrlc = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }