[package]
name = "gkg"
version = "0.1.0"
edition = "2024"
description = "GitLab Knowledge Graph CLI"

[dependencies]
indexer = { path = "../indexer" }
parser-core = { workspace = true }
gitalisk-core = { workspace = true }
clap = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
num_cpus = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }