[profile.default]
default-filter = "not test(export_bindings_)"
[[profile.default.overrides]]
# Apply retries to possibly flaky tests of running binary
filter = "package(gkg) + binary(server) + test(server_)"
retries = { backoff = "exponential", count = 4, delay = "1s" }
[profile.ci]
fail-fast = false
[profile.ci.junit]
path = "junit.xml"
